function [y,y2] = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 03-Dec-2019 16:56:37

persistent Hd;

if isempty(Hd)
    
    N      = 20;          % Order
    Fstop1 = 300;         % First Stopband Frequency
    Fpass1 = 301;         % First Passband Frequency
    Fpass2 = 5000;        % Second Passband Frequency
    Fstop2 = 5001;        % Second Stopband Frequency
    Fs     = 24414.0625;  % Sampling Frequency
    
    h = fdesign.bandpass('n,fst1,fp1,fp2,fst2', N, Fstop1, Fpass1, Fpass2, ...
        Fstop2, Fs);
    
    Hd = design(h, 'equiripple');
    
    set(Hd, 'Arithmetic', 'single');
    
    set(Hd,'PersistentMemory',true);
    
    
    d = designfilt('bandpassiir','FilterOrder',N, ...
        'HalfPowerFrequency1',Fstop1,'HalfPowerFrequency2',Fstop2, ...
        'SampleRate',Fs);
    
end

y = filter(Hd,x);


y2 = filtfilt(d,double(x));

